// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `_pause`, `_play_file`, `_play`, `_seek`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CMD_TX`, `Cmd`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `initialize`

Future<void> playFile({required String path}) =>
    RustLib.instance.api.crateApiPlayerPlayFile(path: path);

Future<void> play() => RustLib.instance.api.crateApiPlayerPlay();

Future<void> pause() => RustLib.instance.api.crateApiPlayerPause();

Future<void> seek({required BigInt secs}) =>
    RustLib.instance.api.crateApiPlayerSeek(secs: secs);
